from django.contrib import admin
from django.urls import include, path
from home.views import *

urlpatterns = [
    path('__reload__/', include('django_browser_reload.urls')),
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('customer', customer, name='customer'),
    path('customerForm', customerForm, name = 'customerForm'),
    path('updatePage/<int:id>', updatePage, name='updatePage'),
    path('deleteData/<int:id>', deleteData, name='deleteData'),
    path('employee', employee, name='employee'),
    path('employeeForm', employeeForm, name='employeeForm'),
    path('updateEmployee/<int:id>', updateEmployee, name='updateEmployee'),
    path('deleteEmployee/<int:id>', deleteEmployee, name='deleteEmployee'),
    path('category', category, name='category'),
    path('categoryForm', categoryForm, name='categoryForm'),
    path('deleteCategory/<int:id>', deleteCategory, name='deleteCategory'),
    path('vendor', vendor, name='vendor'),
    path('vendorForm', vendorForm, name='vendorForm'),
    path('deleteDataVendor/<int:id>', deleteDataVendor, name='deleteDataVendor'),
    path('product', product, name='product'),
    path('productForm', productForm, name='productForm'),
    path('updatePageProduct/<int:id>', updatePageProduct, name='updatePageProduct'),
    path('deleteDataProduct/<int:id>', deleteDataProduct, name='deleteDataProduct'),
    path('purchase', purchase, name='purchase'),
    path('purchaseForm', purchaseForm, name='purchaseForm'),
    path('deleteDataPurchase/<int:id>', deleteDataPurchase, name='deleteDataPurchase'),
    path('stock', stock, name='stock'),
    path('deleteDataStock/<int:id>', deleteDataStock, name='deleteDataStock'),
    path('sales', sales, name='sales'),
    path('salesForm', salesForm, name='salesForm'),
    path('deleteDataSales/<int:id>', deleteDataSales, name='deleteDataSales'),
    path('saleItem', saleItem, name='saleItem'),
    path('salesItemForm/<int:id>', salesItemForm, name='salesItemForm'),
    path('deleteDataSaleItem/<int:id>', deleteDataSaleItem, name='deleteDataSaleItem'),
    path('accounts', accounts, name='accounts'),
    path('deleteDataAccounts/<int:id>', deleteDataAccounts, name='deleteDataAccounts'),
    path('expense', expense, name='expense'),
    path('expenseForm', expenseForm, name='expenseForm'),
    path('deleteExpense/<int:id>', deleteExpense, name='deleteExpense'),
    path('customers/', Customer.as_view(), name='customer'),
    path('customers/<int:pk>/', CustomerDetail.as_view(), name='customer'),
    path('employee/', Employee.as_view(), name='employee'),
    path('employee/<int:pk>/', EmployeeDetail.as_view(), name='employee_detail'),
    path('categories/', Category.as_view(), name='category'),
    path('categories/<int:pk>/', CategoryDetail.as_view(), name='category_detail'),
    path('vendors/', Vendor.as_view(), name='vendor'),
    path('vendors/<int:pk>/', VendorDetail.as_view(), name='vendor_detail'),
    path('products/', Product.as_view(), name='product'),
    path('products/<int:pk>/', ProductDetail.as_view(), name='product_detail'),
    path('purchases/', Purchase.as_view(), name='purchase'),
    path('purchases/<int:pk>/', PurchaseDetail.as_view(), name='purchase_detail'),
    path('stocks/', Stock.as_view(), name='stock'),
    path('stocks/<int:pk>/', StockDetail.as_view(), name='stock_detail'),
    path('sales/', Sales.as_view(), name='sales'),
    path('sales/<int:pk>/', SalesDetail.as_view(), name='sales_detail'),
    path('saleItem/', SaleItemView.as_view(), name='saleItem'),
    path('saleItem/<int:pk>/', SaleItemDetailView.as_view(), name='sale_item_detail'),
    path('saleItemform/<int:pk>/', SalesItemFormView.as_view(), name='sales_item_form'),
    path('delete-sale-item/<int:pk>/', DeleteSaleItemView.as_view(), name='delete_sale_item'),
    path('accounts/', Accounts.as_view(), name='accounts'),
    path('deleteDataAccounts/<int:pk>/', AccountDetail.as_view(), name='deleteDataAccounts'),
    path('expense/', Expense.as_view(), name='expense'),
    path('expenseForm/', ExpenseForm.as_view(), name='expenseForm'),
    path('deleteExpense/<int:pk>/', DeleteExpense.as_view(), name='deleteExpense'),
]

