# Generated by Django 5.1.1 on 2024-10-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_productformdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productformdata',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
