# Generated by Django 5.1.1 on 2024-10-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_productformdata_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productformdata',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productformdata',
            name='price',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productformdata',
            name='unit',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
