# Generated by Django 5.1.1 on 2024-10-03 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_productformdata_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.TextField(max_length=200)),
                ('buy', models.TextField(max_length=200)),
                ('quantity', models.TextField(blank=True, max_length=200, null=True)),
                ('sell', models.TextField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.productformdata')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vendorcontactform')),
            ],
        ),
    ]
