# Generated by Django 5.1.1 on 2024-10-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_stockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customercontactform')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employeecontactform')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stockdata')),
                ('sales_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.salesform')),
            ],
        ),
    ]
