# Generated by Django 5.1.1 on 2024-10-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_purchaseformdata_type_saleitem_type_salesform_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('type', models.CharField(default='Cash', max_length=200)),
            ],
        ),
    ]
