# Generated by Django 5.1.1 on 2024-10-07 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdata',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
