# Generated by Django 5.1.1 on 2024-10-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_accountdata_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdata',
            name='time',
        ),
    ]
