# Generated by Django 5.1.1 on 2024-10-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_accountdata_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
            ],
        ),
    ]
