# Generated by Django 5.1.1 on 2024-10-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_expensedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensedata',
            old_name='name',
            new_name='expense',
        ),
    ]
